### PR TITLE
BUGFIX: Lazy-Load focused node, if it's not fully loaded yet

### LINKED ISSUE #3219: Bug: `Selected element` select a parent node, which is a shortcut.
### Description

The inspector shows an infinite loading icon when a parent node was selected via `Selected element` which is a shortcut.

### Steps to Reproduce

This bug is not reproducible, when the shortcut was already loaded by the ui.

1. Have shortcut with a nested page (and publish them?)
2. Go to a page that is not the shortcut or a descendant of the shortcut
3. Reload the ui to make sure all JavaScript caches about nodes are flushed
4. expect the previous selected node to be still active
5. go to the subpage of the shortcut (without clicking the shortcut itself (gehe nicht über los ziehe keine 200 € ein usw.) )
6. use the `Selected element` dropdown to select the parent / eg the shortcut

[Bildschirmaufzeichnung vom 10.10.2022, 14:17:43.webm](https://user-images.githubusercontent.com/85400359/194864653-6d121aea-4cc3-4d4c-9ce9-14ce6a476a14.webm)

#### Expected behavior

The inspector should work as usually

#### Actual behavior

Infinitive loading to death

### What happened

the `<Inspector />` uses the `renderFallback` with spinner because `node.isFullyLoaded` is falsy or `state.viewConfiguration.tabs` is falsy 

https://github.com/neos/neos-ui/blob/7665b057e7f72fbd56026c106d3bab8528403469/packages/neos-ui/src/Containers/RightSideBar/Inspector/index.js#L344-L350

### Affected Versions

UI:  v8.0.1

### PR DESCRIPTION
**Pull request by grebaldi**
fixes: #3219 

**The Problem**

CR Node representations in the central Redux store have a flag `isFullyLoaded` that indicates whether the node has been loaded with all of its meta data. If the node has only been loaded for being displayed in the document- or content-tree, this flag is absent, otherwise it is set to `true`.

The intention behind flag this was to lazy-load the remaining metadata should it become relevant in a specific interaction context. Apparently though, this mechanism has never been implemented.

**The Solution**

I adjusted the Inspector-saga to perform the aforementioned lazy-load. This fixes #3219, but adds a `plow-js` call, which needs to be kept in mind for #3306.

### CODE REVIEW

File: packages/neos-ui-sagas/src/UI/Inspector/index.js [hunk 1]
```diff
@@ -38,6 +40,18 @@ export function * inspectorSaga({globalRegistry}) {
             //
             if (nextAction.type === actionTypes.CR.Nodes.FOCUS) {
                 yield put(actions.UI.Inspector.closeSecondaryInspector());
+
+                const focusedNode = yield select(getFocusedNode);
+                if (!$get('isFullyLoaded', focusedNode)) {
```
Comment (mhsdesign) [inline packages/neos-ui-sagas/src/UI/Inspector/index.js:45]: cant we just use opt chaining in 7.3? ^^

Comment (grebaldi) [reply packages/neos-ui-sagas/src/UI/Inspector/index.js:45]: we can't, sadly

Comment (mhsdesign) [reply packages/neos-ui-sagas/src/UI/Inspector/index.js:45]: okay then thats fine with me ;)

**Review by markusguenther — APPROVED** [review]
Great that you tackled the issue. Could reproduce the bug and your solution works fine :)
