### PR TITLE
BUGFIX: createNew doesn't set title of new node

### LINKED ISSUE #1764: createNew in references editor doesn't write given string to title of new node
### Description

Created a references editor for tagging a node with the createNew option. Followed the instructions here: http://neos.readthedocs.io/en/stable/References/PropertyEditorReference.html#property-type-reference-references-referenceeditor-referenceseditor-reference-selection-editors

New Node is created correctly in the given path and with the given type.
But the given string is not passed to the created Nodes Title.

The option titleProperty: 'title' doesn't help either.

Am i missing something, or is this a bug?

### Steps to Reproduce

1. Create a node type with property type references selecting only my "FormatD.Website:TeamDepartment" - NodeType
2. Option createNew with given Path and Type "FormatD.Website:TeamDepartment"
3. New Node is created properly, but doesn't set the given string as title for the new node

Code:
```
'FormatD.Website:TeamDepartment':
  superTypes:
    'Neos.Neos:Content': TRUE
  ui:
    label: 'Team Department'
    group: 'general'
    inspector:
      groups:
        settings:
          label: 'Settings'
  properties:
    title:
      type: string
      ui:
        label: 'Title'
        inspector:
          group: 'settings'
```

```
department:
  type: references
  ui:
    label: 'Department'
    inspector:
      group: 'settings'
      editorOptions:
        nodeTypes: ['FormatD.Website:TeamDepartment']
        createNew:
          path: /sites/formatd-website/main/node-0ra4dr6pc4pod/main/node-ybf6qemgwhb5o/filter
          type: 'FormatD.Website:TeamDepartment'
          titleProperty: 'title'
```

#### Expected behavior

As described in the Docs:
"The given string is passed to the title property of the new node."

#### Actual behavior

The given string is NOT passed to the title property of the new node.
The Default Node Name is displayed instead and the title property of my new node stays empty.
Also no other property like name etc is replaced.

bildschirmfoto 2018-04-11 um 10 06 23
create New is working

bildschirmfoto 2018-04-11 um 10 07 32
strange that already here the string ist not passed

bildschirmfoto 2018-04-11 um 10 06 46
Results in structure: Node Types with default Name, and no given string. The first ones were added manually. Changing title in inspector does work and is also selectable in the reference editor.

### Affected Versions

Neos:
3.3.9

UI:
1.0.9

### PR DESCRIPTION
**Pull request by christophengelmayer**
The title set in references editor wasn't used for creating the new content node.

Fixes #1764

### CODE REVIEW

File: Classes/NodeCreationHandler/ContentTitleNodeCreationHandler.php [hunk 1]
```diff
@@ -0,0 +1,42 @@
...
+     * @param array $data incoming data from the creationDialog
+     * @return void
+     */
+    public function handle(NodeInterface $node, array $data)
+    {
+        if ($node->getNodeType()->isOfType('Neos.Neos:Content')) {
+            if (isset($data['title'])) {
+                $node->setProperty('title', $data['title']);
+            }
+            // $node->setProperty('uriPathSegment', $this->nodeUriPathSegmentGenerator->generateUriPathSegment($node, (isset($data['title']) ? $data['title'] : null)));
```
Comment (dimaip) [inline Classes/NodeCreationHandler/ContentTitleNodeCreationHandler.php]: code comment?

File: Classes/NodeCreationHandler/ContentTitleNodeCreationHandler.php [hunk 2]
```diff
@@ -0,0 +1,42 @@
...
+use Neos\Flow\Annotations as Flow;
+use Neos\Neos\Utility\NodeUriPathSegmentGenerator;
+
+class ContentTitleNodeCreationHandler implements NodeCreationHandlerInterface
+{
+    /**
+     * @Flow\Inject
+     * @var NodeUriPathSegmentGenerator
+     */
+    protected $nodeUriPathSegmentGenerator;
```
Comment (dimaip) [inline Classes/NodeCreationHandler/ContentTitleNodeCreationHandler.php]: Is this needed? Probably not...

File: Classes/NodeCreationHandler/ContentTitleNodeCreationHandler.php [hunk 3]
```diff
@@ -0,0 +1,33 @@
...
+    /**
+     * Set the node title for the newly created Content node
+     *
+     * @param NodeInterface $node The newly created node
+     * @param array $data incoming data from the creationDialog
+     * @return void
+     */
+    public function handle(NodeInterface $node, array $data)
+    {
+        if ($node->getNodeType()->isOfType('Neos.Neos:Content')) {
```
Comment (dimaip) [inline Classes/NodeCreationHandler/ContentTitleNodeCreationHandler.php]: It's better to not hardcode `'Neos.Neos:Content'`, there's a way to get it from Neos somehow

Comment (dimaip) [reply Classes/NodeCreationHandler/ContentTitleNodeCreationHandler.php]: Nevermind
