### PR TITLE
TASK: Adjust PrimaryToolbar z-index

### LINKED ISSUE #2140: Media tool close button overlays user menu dropdown
### Description
Wrong z-index for close button on media tools, e.g. cropping tool. 

### Steps to Reproduce
1. Open the media module or the cropping module from within the inspector 
2. Open the user menu

#### Expected behavior
image

#### Actual behavior
image

### Affected Versions
Neos: v3.3.14
UI: v1.1.2 - v1.3.3

### PR DESCRIPTION
**Pull request by johannessteu**
Resolves #2140

### CODE REVIEW

File: packages/build-essentials/src/styles/styleConstants.js [hunk 1]
```diff
@@ -26,7 +26,7 @@ const config = {
         fullScreenClose: ['context'],
         drawer: ['context'],
         bar: ['context'],
-        primaryToolbar: ['context'],
+        primaryToolbar: '2',
```
Comment (markusguenther) [inline packages/build-essentials/src/styles/styleConstants.js]: We have old views (like the image media select) and there the z-index of the close button is 3. So we need a minimum value of 4.

**Comment by johannessteu** [comment]
This is just a mess 😓 . Had to adjust the flashMessageContainer as well ...

**Comment by markusguenther** [comment]
Looks good to me :)
