### PR TITLE
TASK: Add titles to select options

### LINKED ISSUE #2271: Full link is no longer shown as tooltip of LinkInput
### Description

In the old UI, the full link was shown when hovering the link editor in the inspector. On the new UI, that functionality is missing. When using multiple dimensions, the link gets prefixed with the dimension path segment, taking up too much space to see the complete link. 
Screenshot

### Steps to Reproduce

1. Set a link in the inspector (using `Neos.Neos/Inspector/Editors/LinkEditor`)
2. Apply the changes
3. Hover the link editor

#### Expected behavior

The full link should be shown as tooltip.

#### Actual behavior

No tooltip is shown.

### Affected Versions

Neos: 3.3.16

UI: 1.4.1

### PR DESCRIPTION
**Pull request by sbruggmann**
Fixes #2271

### CODE REVIEW

File: packages/react-ui-components/src/SelectBox_Option_MultiLineWithThumbnail/selectBox_Option_MultiLineWithThumbnail.js [hunk 1]
```diff
@@ -42,9 +42,9 @@ class SelectBox_Option_MultiLineWithThumbnail extends PureComponent {
         return (
             <ListPreviewElement {...rest} icon={icon} className={finalClassNames}>
                 {Boolean(imageUri) && <img src={imageUri} alt={label} className={theme.multiLineWithThumbnail__image}/>}
-                <span>{label}</span>
-                {Boolean(secondaryLabel) && <span className={theme.multiLineWithThumbnail__secondaryLabel}>{secondaryLabel}</span>}
-                {Boolean(tertiaryLabel) && <span className={theme.multiLineWithThumbnail__tertiaryLabel}>{tertiaryLabel}</span>}
+                <span title={label}>{label}</span>
```
Comment (dimaip) [inline packages/react-ui-components/src/SelectBox_Option_MultiLineWithThumbnail/selectBox_Option_MultiLineWithThumbnail.js]: How does it help to have a title identical to the label?

Comment (sbruggmann) [reply packages/react-ui-components/src/SelectBox_Option_MultiLineWithThumbnail/selectBox_Option_MultiLineWithThumbnail.js]: It helps on long strings, especially for page titles and URLs
