### PR TITLE
BUGFIX: properly pass node hidden in menu state to UI

### LINKED ISSUE #4009: BUG: initial hiddenInMenus state in document tree incorrect
When initially loading the UI, all document nodes are marked as not hidden in menu, i.e. with a white icon. That includes nodes that _are_ actually hidden in menus. This changes once those are clicked; they will get the correct grey icon then.

Expected behavior: The hidden in menu state should be visible from the start.

Neos Version: 9.0.6
Neos UI Version: 9.0.2

### PR DESCRIPTION
**Pull request by nezaniel**
This adjusts the node info helper to properly pass the node hidden state to the UI

Resolves: #4009 

Further info: see issue

### CODE REVIEW

**Review by skurfuerst — APPROVED** [review]
makes sense, LGTM by reading. I checked the source code of Neos to see that it now references hiddenInMenu and NOT hiddenInIndex.

File: Classes/Fusion/Helper/NodeInfoHelper.php [hunk 1]
```diff
@@ -104,7 +104,7 @@ public function renderNodeWithMinimalPropertiesAndChildrenInformation(
             // ensure _isHidden is sent to hidden nodes are correctly shown in the tree.
             // TODO: we should export this correctly named, but that needs changes throughout the JS code as well.
             '_hidden' => $node->tags->withoutInherited()->contain(NeosSubtreeTag::disabled()),
-            '_hiddenInIndex' => $node->getProperty('hiddenInMenu'),
+            'hiddenInMenu' => $node->getProperty('hiddenInMenu'),
```
Comment (Sebobo) [inline Classes/Fusion/Helper/NodeInfoHelper.php:107]: Hm this was done for compatibility reasons. I guess for now we should keep both names here until we adjust all of them.

**Review by Sebobo — CHANGES_REQUESTED** [review]
Thx! Works, but I think we should keep the old property additionally for compatibility in plugins for now.

File: Classes/Fusion/Helper/NodeInfoHelper.php (hunk 1 above)
Comment (nezaniel) [reply Classes/Fusion/Helper/NodeInfoHelper.php:107]: afaik the whole UI was already refactored to use the new name, which is why this no longer worked.

Comment (nezaniel) [reply Classes/Fusion/Helper/NodeInfoHelper.php:107]: (see https://github.com/neos/neos-ui/pull/3987)

Comment (Sebobo) [reply Classes/Fusion/Helper/NodeInfoHelper.php:107]: Yes but plugins. Wouldn't hurt much to keep both for now, until we clean up.

Comment (nezaniel) [reply Classes/Fusion/Helper/NodeInfoHelper.php:107]: ah, of course, /done

**Review by Sebobo — APPROVED** [review]
Thx!
