### PR TITLE
BUGFIX: Perform additional search for links that look like externals or emails

### LINKED ISSUE #3016: BUG: looksLikeExternalLink() too unspecific
### Description

We have several Product-Nodetypes defined as Document-Nodetypes with a title of for example 12.233 (the SKU). When entering this sku in the link feature of the inline editable editor, `Neos.Neos.Ui:packages/neos-ui-editors/src/Library/LinkInput.js` thinks, this is a url as the Regex `^[\w.-]{2,}\.[\w]{2,10}$` in `looksLikeExternalLink()` is too specific in my opinion. `\w` contains digits, too even though TLDs AFAIK must not contain digits. This causes NEOS to stop searching the node tree and showing the `Format as HTTP Link?` message. Is there any reason to keep this regex that unspecific?

### Steps to Reproduce

1. Create a node with the title `23.233`.
2. Add an inline editable text and search for this node to link it using the link feature of ckeditor.

#### Expected behavior

It will search the node tree and display `23.233` as a suggestion in the dropdown.

#### Actual behavior

It will stop searching the node tree when typing the `23.23` because it considers the string an http link. It then shows `Format as HTTP Link?`.

### Affected Versions

All

### PR DESCRIPTION
**Pull request by grebaldi**
fixes: #3016 

|before|after|
|-|-|
|Screenshot_2023-05-11_16-44-44 3016 - before|Screenshot_2023-05-12_12-22-58 3016 - after 2 |

**The problem**

The link input will recognize certain strings as E-Mail addresses or probable external links (with very broad coverage there). If it does so, it won't perform a search on nodes or assets but will immediately show a suggestion like "Format as external link?".

It is however quite possible that the user is actually searching for a document or asset that is titled after an E-mail address or anything that may look like a domain. #3016 mentions an example of a document with an SKU as a title that was recognized as an external link and thus could not be found by the link input.

**The solution**

@RobReckham suggested in #3016 to adjust how `looksLikeExternalLink` recognizes external links. I figured however that it may be too difficult to find an actually satisfactory regex that would cover all possible scenarios properly.

So, I decided to go a different route and leave the algorithm as it is. Instead, the link input now performs the search for nodes and assets even if the input looks like an E-Mail address or external link. The actions "Format as external link?" or "Format as e-mail?" are still being displayed if `looksLikeExternalLink` recognizes the input as such, but they're now entirely optional.

### CODE REVIEW

**Comment by Sebobo** [comment]
Awesome, thx!

Should we adjust the `Without Group` label to something else? I think it's a bit confusing right now. 
Maybe `Format options`?

**Comment by grebaldi** [comment]
@Sebobo Yep, that makes sense. But I'm not sure whether additional translations would still allow this to be a bugfix. If not, I'd opt for adding the label in an additional PR for 9.0 post-upmerge.

**Comment by Sebobo** [comment]
IMO that is fine, we had bugfixes for missing translations too, so it would just cause the next bug issue ;)

**Review by crydotsnake — APPROVED** [review]
Tested and works as expected!

**Review by mhsdesign — APPROVED** [review]
Works splendidly!

comparison:

| before | after |
| -------| ----- |
| image | image |
| image | image |
| image | image |
| image | image |

**Comment by mhsdesign** [comment]
I added the missing translation definition in en and de ;)

File: packages/neos-ui-editors/src/Library/LinkInput.js [hunk 1]
```diff
@@ -150,41 +150,43 @@ export default class LinkInput extends PureComponent {
...
+                        searchOptions.forEach(searchOption => {
                             searchOption.group = 'assetSourceLabel' in searchOption ? searchOption.assetSourceLabel : this.props.i18nRegistry.translate('Neos.Neos:Main:document');
-                            return searchOption;
+                            groupedSearchOptions.push(searchOption);
                         });
+
                         this.setState({
                             isLoading: false,
-                            searchOptions: groupedSearchOption
+                            searchOptions: [...groupedSearchOptions]
```
Comment (mhsdesign) [inline packages/neos-ui-editors/src/Library/LinkInput.js:189]:
```suggestion
                            searchOptions: groupedSearchOptions
```

nitpick: is there a reason for this copy?

**Review by bwaidelich — COMMENTED** [review]
I can't judge the code (due to my js ignorance) but I love this change, thank you! :)

File: packages/neos-ui-editors/src/Library/LinkInput.js (hunk 1 above)
Comment (grebaldi) [reply packages/neos-ui-editors/src/Library/LinkInput.js:189]: Yep. At line 177 you'll see that `groupedSearchOptions` is already put into state. State then holds a reference to `groupedSearchOptions` which gets mutated in line 184. So to make sure that the changes made to `groupedSearchOptions` after the search results have been fetched also lead to a changed reference, `groupedSearchOptions` needs to be copied at this point.

File: packages/neos-ui-editors/src/Library/LinkInput.js [hunk 2]
```diff
@@ -150,41 +150,43 @@ export default class LinkInput extends PureComponent {
...
+
             this.props.linkLookupDataLoader.search(this.getDataLoaderOptions(), searchTerm)
                 .then(searchOptions => {
                     if (searchTermWhenLookupWasTriggered === this.state.searchTerm) {
-                        const groupedSearchOption = searchOptions.map(searchOption => {
+                        searchOptions.forEach(searchOption => {
                             searchOption.group = 'assetSourceLabel' in searchOption ? searchOption.assetSourceLabel : this.props.i18nRegistry.translate('Neos.Neos:Main:document');
-                            return searchOption;
+                            groupedSearchOptions.push(searchOption);
                         });
```
Comment (mhsdesign) [inline packages/neos-ui-editors/src/Library/LinkInput.js:185]:
```suggestion
                        });
```

File: packages/neos-ui-editors/src/Library/LinkInput.js (hunk 1 above)
Comment (mhsdesign) [reply packages/neos-ui-editors/src/Library/LinkInput.js:189]: ahh i see, because there would be no diff in setState to the previous one... so technically it would properly cleaner to make a copy already before? But fine with me. Thanks for explaining - i imagined something like this, but its not always super obvious ^^ (i oversaw that 177 happens always and not conditionally ^^)
