### PR TITLE
TASK: Make NodeTreeFilter more robust

### LINKED ISSUE #1505: NodeTypeFilter glitches
image

- No close button in nodetypes filter
- Select nodetype filter, then click on the header, then try to select again: doesn't work releably

### PR DESCRIPTION
**Pull request by johannessteu**
Fixes #1505

### CODE REVIEW

**Comment by johannessteu** [comment]
The issue with the dropdown is that the drag&drop targetzones got the same or even a higher zinde-x compared to the selectbox dropdown. So sometimes you click that zone instead of the item in your list

http://g.recordit.co/xyiNFwTaFF.gif

File: packages/build-essentials/src/styles/styleConstants.js [hunk 1]
```diff
@@ -29,7 +29,7 @@ const config = {
         primaryToolbar: ['context'],
         checkboxInput: ['context'],
         dropdownContents: ['context'],
-        selectBoxContents: ['context'],
+        selectBoxContents: '3',
```
Comment (dimaip) [inline packages/build-essentials/src/styles/styleConstants.js]: Yep, this is OK for now, the z-index concept is kind of broken now, needs re-thinking

Comment (mstruebing) [reply packages/build-essentials/src/styles/styleConstants.js]: we have an own issue for that afaik :P
