### PR TITLE
BUGFIX: fallback to the first tab when tab index is out of bounds

### LINKED ISSUE #826: When switching focused node, inspector becomes blank if the focused nodetype doesn't have that group
**[<- must-have for 1.0.0](https://github.com/neos/neos-ui/issues/687)**

Steps to reproduce:
1. open in inspector some group that only this nodetype has, e.g. SEO group
2. focus a node that doesn't have such group, e.g. Text
3. contemplate inspector staying blank, instead of focusing to first available group in the new nodetype

image

### PR DESCRIPTION
**Pull request by dimaip**
Fixes #826

### CODE REVIEW

File: packages/react-ui-components/src/Tabs/tabs.js [hunk 1]
```diff
@@ -73,13 +73,20 @@ export default class Tabs extends PureComponent {
         );
     }
 
+    getActiveTab() {
```
Comment (skurfuerst) [inline packages/react-ui-components/src/Tabs/tabs.js]: I'd call this "activeTabIndex"; and also change the state property to "activeTabIndex" - is more clear, wdyt?

Comment (dimaip) [reply packages/react-ui-components/src/Tabs/tabs.js]: The problem with renaming state `activeTab` is that it has related prop `activeTab`, which is a part of component's API, and since we publish this package to npm and already version it, that would require a version bump... Frankly I'd just ignore it, but if you insist I can take care.

Comment (skurfuerst) [reply packages/react-ui-components/src/Tabs/tabs.js]: OK then we keep it as is. Fine ;)
