### PR TITLE
BUGFIX: Fix error msg of CountValidator

### LINKED ISSUE #4034: BUG: Count Validator showing wrong error message
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Currently when you have type: references and add a count validator the error message in backend is shown without the minimum and maximum integers that are in the yaml
`
The count must be between {minimum} and {maximum}.
`

Example from my Project:
```
products:
      type: references
      defaultValue: []
      ui:
        label: 'Products'
        reloadIfChanged: true
        inspector:
          group: 'products'
          hidden: 'ClientEval:node.properties.listType != "static"'
          editorOptions:
            nodeTypes:
              - 'Acme.Blog:Test.Test'
      validation:
        'Neos.Neos/Validation/CountValidator':
          minimum: '0'
          maximum: '3'
```

### Expected Behavior

When you have type: references and add a count validator the error message in backend is shown with the minimum and maximum integers that are in the yaml
`
The count must be between 0 and 3.
`

### Steps To Reproduce

1. create property with type references
2. Neos.Neos/Validation/CountValidator with minimum of 0 and maximum 3. (the numbers can of course be different)
3. go into the backend and put 4 references in

### Environment

```markdown
- Flow: 8.1.2
- Neos: 8.1.2
- PHP: 8.1
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by JamesAlias**
**What I did**
Fixed [issue 4034](https://github.com/neos/neos-development-collection/issues/4034) in Neos Repo.

**How I did it**
Fixed regression.
Wrote a unit test that checks that the validation function returns an React element with the correct props in case of an error.

**How to verify it**
Run tests.

Screenshot 2023-02-16 at 12 08 16 PM
Screenshot 2023-02-16 at 12 08 10 PM

### CODE REVIEW

File: packages/neos-ui-validators/src/Count/index.tsx [hunk 1]
```diff
@@ -33,13 +33,9 @@ const Count = (value: any, validatorOptions: CountOptions) => {
 
     const {length} = Object.keys(value);
 
-    if (length === 0) {
```
Comment (dlubitz) [inline packages/neos-ui-validators/src/Count/index.tsx:36]: The removal of this check, removes the ability to apply the validation to a optional property. I'd like to keep it as it was, as it works the same for other neos validators. If you need to validate more than one, you can simply add the NotEmptyValidator.

**Review by dlubitz — CHANGES_REQUESTED** [review]

File: packages/neos-ui-validators/src/Count/index.tsx (hunk 1 above)
Comment (JamesAlias) [reply packages/neos-ui-validators/src/Count/index.tsx:36]: Done. 
Thanks for clearing that one up. For me it felt odd at first but I can now understand _why_ this is the way you want it to work.

**Review by dlubitz — APPROVED** [review]

**Comment by ahaeslich** [comment]
Is 8.3 the right target branch?

**Comment by ahaeslich** [comment]
It seems to be a regression introduced with 8.0 in #2996.

**Comment by JamesAlias** [comment]
> It seems to be a regression introduced with 8.0 in #2996.

Should I rebase to 8.0?

**Comment by ahaeslich** [comment]
> > It seems to be a regression introduced with 8.0 in #2996.
> 
> Should I rebase to 8.0?

If you rebase your branch on a older history you would transfer all changes since the 8.0 release and not just this one. It will be easier if you start a new branch based on 8.0 and cherry pick your changes.

**Comment by JamesAlias** [comment]
> If you rebase your branch on a older history you would transfer all changes since the 8.0 release and not just this one. It will be easier if you start a new branch based on 8.0 and cherry pick your changes.

Yeah I know, but for me I still call it 'rebasing', sry 😄

**Review by ahaeslich — APPROVED** [review]
