### PR TITLE
BUGFIX: 3574 initialize foreign referenced nodes

### LINKED ISSUE #3574: BUG: Neos UI crashes after applying references with `Neos.NodeTypes.ContentReferences:ContentReferences`
### Description

If I add references to the `Neos.NodeTypes.ContentReferences:ContentReferences` and apply them, some errors are thrown to the console. After that, I don't get any feedback on the UI to further action. E.g if I click the "publish" button afterward I don't get any feedback, but the publish is happen in the background.

I've this issue with Neos 7.3, but the "Key must be a string" errors are also shown in Neos UI 8.3, but not the last one at `watchServerFeedback`.

### Steps to Reproduce

1. Create node with type `Neos.NodeTypes.ContentReferences:ContentReferences`
2. Select a random reference in ReferenceEditor
3. Click apply

#### Actual behavior

image

### Affected Versions

Neos: 7.3.13
UI: 7.3.17

### PR DESCRIPTION
**Pull request by mhsdesign**
resolves: #3574

actual fix instead of hotfix: #3575 and https://github.com/neos/neos-development-collection/pull/4399

similar to @grebaldi solution at: #3364

**What I did**

**How I did it**

**How to verify it**

revert: https://github.com/neos/neos-development-collection/pull/4399 and try to follow #3574

### CODE REVIEW

File: packages/neos-ui/src/manifest.js [hunk 1]
```diff
@@ -513,7 +514,7 @@ manifest('main', {}, globalRegistry => {
     // When the server advices to replace a node (e.g. on property change), put the delivered html to the
     // correct place inside the DOM
     //
-    serverFeedbackHandlers.set('Neos.Neos.Ui:ReloadContentOutOfBand/Main', (feedbackPayload, {store, globalRegistry}) => {
+    serverFeedbackHandlers.set('Neos.Neos.Ui:ReloadContentOutOfBand/Main', async (feedbackPayload, {store, globalRegistry}) => {
```
Comment (mhsdesign) [inline packages/neos-ui/src/manifest.js:517]: idk, if its wise to make this async ... sure the whole feedback is async, but now from the feedback collection this will be handled last despite of the order - i think

**Comment by Sebobo** [comment]
Should we go with both PRs just to be one the safe side?

**Comment by mhsdesign** [comment]
No I rather not - I like to be more explicit and if we just ignore any unexpected input wrong behaviour will later be worse to debug then if there was an exception.

we can still write a safeguard and log an error to the console if you want…

**Comment by Sebobo** [comment]
Yes then I will adjust my PR to do that. The code there just relies too much on data being there.

File: packages/neos-ui/src/manifest.js (hunk 1 above)
Comment (mhsdesign) [reply packages/neos-ui/src/manifest.js:517]: no the execution starts immediately, so there should be no change of behavior for the "happy" case.

```js
console.log('main 1');

const asyncAwait = async () => {
    console.log('asyncAwait 2');

    await new Promise(r => r());

    console.log('asyncAwait 3');
}

asyncAwait();

const promiseCallback = () => {
    console.log('promiseCallback 4');

    new Promise(r => r()).then(
        () => console.log('promiseCallback 5')
    );
}

promiseCallback();

console.log('main 6');
```

logs:
```
[Log] main 1
[Log] asyncAwait 2
[Log] promiseCallback 4
[Log] main 6
[Log] asyncAwait 3
[Log] promiseCallback 5
```

**Comment by dlubitz** [comment]
This is the PR for fusion side: https://github.com/neos/neos-development-collection/pull/4399

**Review by dlubitz — APPROVED** [review]
I like! ❤️  I can't evaluate the technical solution, but it looks reasonable.

File: packages/neos-ui/src/manifest.js [hunk 2]
```diff
@@ -543,6 +544,27 @@ manifest('main', {}, globalRegistry => {
 
         const children = findAllChildNodes(contentElement);
 
+        // in case there are foreign refernced nodes, we need to put them into the store:
```
Comment (grebaldi) [inline packages/neos-ui/src/manifest.js]:
```suggestion
        // in case there are foreign referenced nodes, we need to put them into the store:
```

**Review by grebaldi — COMMENTED** [review]
LGTM code-wise.

However, I was unable to reproduce the issue as per description in #3574.

**Comment by mhsdesign** [comment]
> However, I was unable to reproduce the issue as per description in https://github.com/neos/neos-ui/issues/3574.

Maybe because we have the hotfix https://github.com/neos/neos-ui/pull/3575 already merged? (So the console output should still complain, but less so)

Also for future reviewers: Make sure to revert https://github.com/neos/neos-development-collection/pull/4399 once its merged ;)

**Comment by grebaldi** [comment]
@mhsdesign 
> Maybe because we have the hotfix #3575 already merged? (So the console output should still complain, but less so)

Oh yes, didn't see that :)
