### PR TITLE
TASK: Update NodeInfoView to ESCR changes

### LINKED ISSUE #3434: 9.0 TASK: Update `NodeInfoView` to ESCR changes
### Description

In previous neos version, the `NodeInfoView` showed the following information in the inspector:

- `identifier`
- `properties._creationDateTime`
- `properties._lastModificationDateTime`
- `properties._lastPublicationDateTime`
- `properties._path`
- `properties._name`
- `nodeType`

In the current 9.0-dev version only `identifier` and `nodeType` show correct data.

Needed to complete this task: neos/neos-development-collection#4092

### Steps to Reproduce

1. Select a node
2. Got to the `Metadata`-Tab in the inspector
3. Open the Accordion ` Additional info`

### Affected Versions

- Neos: 9.0-dev
- UI: 9.0-dev

### PR DESCRIPTION
**Pull request by kitsunet**
Fixes: #3434
Relates: #3480

### CODE REVIEW

File: packages/neos-ui-views/src/NodeInfoView/index.js [hunk 1]
```diff
@@ -28,11 +28,11 @@ export default class NodeInfoView extends PureComponent {
         const node = getNodeByContextPath(focusedNodeContextPath);
         const properties = {
             identifier: $get('identifier', node),
-            created: $get('properties._creationDateTime', node),
-            lastModification: $get('properties._lastModificationDateTime', node),
-            lastPublication: $get('properties._lastPublicationDateTime', node),
-            path: $get('properties._path', node),
-            name: $get('properties._name', node) ? $get('properties._name', node) : '/'
+            created: $get('creationDateTime', node),
+            lastModification: $get('lastModificationDateTime', node),
```
Comment (ahaeslich) [inline packages/neos-ui-views/src/NodeInfoView/index.js:32]: `lastModification` AND `lastPublication` can be `null`. Therefore we need to add a check for `lastModification` in line 46 as already implemented in line 50.

Comment (kitsunet) [reply packages/neos-ui-views/src/NodeInfoView/index.js:32]: as I am doing it, I wonder, do we want to keep the row and just show nothing? Otherwise the Display jumps between nodes

**Review by ahaeslich — APPROVED** [review]
