### PR TITLE
TASK: Improve ckeditor plugin migration to Neos 8.2 and up #3452

### LINKED ISSUE #3452: TASK: Improve ckeditor plugin migration to Neos 8.2 and up
### Description

currently an unreadable error is thrown which doesnt directly mention that it is a ckeditor plugin wich causes the error.
there are no upgrade instructions at: https://docs.neos.io/api/upgrade-instructions/8/upgrade-instructions-8-1-8-2

edit: there are actually instructions but i find them hard to understand 😂 

related: https://github.com/neos/neos-ui/issues/3287

[Description of the bug or feature]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

#### Expected behavior

[What you expected to happen]

#### Actual behavior

[What actually happened]

### Affected Versions

Neos:

UI:

You can get this information by running `composer show` or using the package management module within Neos.
The UI version can also be found inside the left sidebar after version 1.0.3.

### PR DESCRIPTION
**Pull request by mhsdesign**
solves #3452

**What I did**

throw a nicer error:

```
Neos.Ui: Youre probably using a CKeditor plugin which needs to be rebuild.
see https://github.com/neos/neos-ui/issues/3287

Original Error:

TypeError: Class constructor et cannot be invoked without 'new'
    at new CodeFormating (http://127.0.0.1:8081/_Resources/Static/Packages/Neos.Demo/Scripts/CodeTagPlugin/Plugin.js?ee34d796:37088:115)
    at http://127.0.0.1:8081/_Resources/Static/Packages/Neos.Neos.Ui/Build/Host.js?ea7d7a0a:516:151225
    at new Promise (<anonymous>)
    at h (http://127.0.0.1:8081/_Resources/Static/Packages/Neos.Neos.Ui/Build/Host.js?ea7d7a0a:516:150962)
    at f (http://127.0.0.1:8081/_Resources/Static/Packages/Neos.Neos.Ui/Build/Host.js?ea7d7a0a:516:150735)
    at Array.map (<anonymous>)
    at tx.init (http://127.0.0.1:8081/_Resources/Static/Packages/Neos.Neos.Ui/Build/Host.js?ea7d7a0a:516:150595)
    at A5.initPlugins (http://127.0.0.1:8081/_Resources/Static/Packages/Neos.Neos.Ui/Build/Host.js?ea7d7a0a:516:232527)
    at http://127.0.0.1:8081/_Resources/Static/Packages/Neos.Neos.Ui/Build/Host.js?ea7d7a0a:517:6881
    at new Promise (<anonymous>)
```

**How I did it**

**How to verify it**

### CODE REVIEW

File: packages/neos-ui-ckeditor5-bindings/src/ckEditorApi.js [hunk 1]
```diff
@@ -78,7 +78,13 @@ export const createEditor = store => options => {
 
             editor.model.document.on('change', () => handleUserInteractionCallback());
             editor.model.document.on('change:data', debounce(() => onChange(cleanupContentBeforeCommit(editor.getData())), 500, {maxWait: 5000}));
-        }).catch(e => console.error(e));
+        }).catch(e => {
+            if (e instanceof TypeError && e.message.match(/Class constructor .* cannot be invoked without 'new'/)) {
+                console.error("Neos.Ui: Youre probably using a CKeditor plugin which needs to be rebuild.\nsee https://github.com/neos/neos-ui/issues/3287\n\nOriginal Error:\n\n" + e.stack);
```
Comment (crydotsnake) [inline packages/neos-ui-ckeditor5-bindings/src/ckEditorApi.js:83]: `\nsee` is this a typo? shoudlnt it be `\n\see` ?

Comment (mhsdesign) [reply packages/neos-ui-ckeditor5-bindings/src/ckEditorApi.js:83]: Hi ;) no I believe it’s called something like c-style character in strings escape (works in double quotes) and \n is equivalent to ascii 10 or simply put a newline ;)

**Review by crydotsnake — APPROVED** [review]

**Comment by mhsdesign** [comment]
@markusguenther ill merge this ;) Here is the verification that it works:

before:

image


after:
image

**Review by markusguenther — APPROVED** [review]

**Comment by mhsdesign** [comment]
Was upmerged to 8.3 via 66bcff127ec5bc593491b2b05f622b8fd3a8b69e
